import { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useQuery } from "react-query";

import styles from "../styles/Home.module.css";
import Search from "../components/search";
import { client } from "../utils/axios";

export default function Home() {
  const { data, error } = useQuery("/random.php", a => {
    return client.get(a.queryKey[0]).then(r => r.data);
  });

  useEffect(() => {
    console.log(data);
  }, [data]);

  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="sticky top-0 p-2 shadow-md bg-white">
        <nav>
          <Link href="/">
            <a className="block text-blue-700 my-2 mx-12 font-bold text-3xl">
              MealDB
            </a>
          </Link>
        </nav>
      </header>

      <section className="max-w-screen-md mx-auto my-4 flex justify-center flex-col items-stretch">
        <Search />

        <div role="heading" aria-level={2} className="flex justify-center m-4">
          <h1 className="m-0">
            Random <span className="text-blue-600">Meals</span>
          </h1>
        </div>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </main>
  );
}
